spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/cartdb
    username: root
    password: drisht123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
